### ISSUE TITLE
Aborting/quitting client is very broken

### ISSUE THREAD

**Issue by parkan** [mediachain/mediachain-client#20]
Trying to Ctrl-C results in 

```
deduplicating getty artists.  This may take a while...
Parsed 1 entries, 1 unique artistsRPC error inserting entity: RemoteError(code=StatusCode.UNKNOWN, details="")

done deduplicating artists
^CTraceback (most recent call last):
  File "/Users/arkadiy/mine/mediachain-client/venv/bin/mediachain", line 11, in <module>
    sys.exit(main())
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/cli/main.py", line 114, in main
    fn(ns)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/cli/main.py", line 107, in <lambda>
    ns.download_thumbs)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/getty/ingest.py", line 23, in ingest
    transactor, datastore, dir_root, max_num, download_thumbs
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/getty/ingest.py", line 96, in getty_artefacts
    thumbnail_ref=thumbnail_ref
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/getty/ingest.py", line 45, in getty_to_mediachain_objects
    entity_ref = transactor.insert_canonical(entity)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/mediachain/transactor/client.py", line 29, in insert_canonical
    ref = self.client.InsertCanonical(req, timeout)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/grpc/framework/crust/implementations.py", line 75, in __call__
    protocol_options, metadata, request)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/grpc/framework/crust/_calls.py", line 109, in blocking_unary_unary
    return next(rendezvous)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/grpc/framework/crust/_control.py", line 425, in next
    self._condition.wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/arkadiy/mine/mediachain-client/venv/lib/python2.7/site-packages/concurrent/futures/thread.py", line 39, in _python_exit
    t.join(sys.maxint)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 960, in join
    self.__block.wait(delay)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
Error in sys.exitfunc:
```

(and it still doesn't exit)

Seems like you need to assign an interrupt handler maybe?

**Comment by autoencoder** [comment]
Here was the temporary "fix" used by the Indexer ingester...

``` python
        try:
           #code here
        except:
            from time import sleep
            import traceback, sys, os
            for line in traceback.format_exception(*sys.exc_info()):
                print line,
            sleep(1) 
            os._exit(-1)
```

**Comment by yusefnapora** [comment]
k; I'll wrap `main` with that for now.  Hopefully we can find a real fix eventually :)

**Comment by yusefnapora** [comment]
I think the real issue is an exception handler in gRPC catching the `SystemExit` exception.  I dug into that a while ago, and I think that a fix might have made it into master, but isn't released yet.  I'll see if I can find that again so we can track it

**Comment by parkan** [comment]
Closing for now, can reopen with real fix as needed
